### ISSUE TITLE
issue with perl when installing roadies with conda 

### ISSUE THREAD

**Issue by usergenomics13** [TurakhiaLab/ROADIES#28]
Hi 
I'm trying to install roadies with conda and faced an error with perl.  I would appreciate your help how to solve this.
```
conda create -n road python=3.9
conda activate road
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install bioconda::roadies
```

This is the summarized output log:
```
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done
## Package Plan ##
  environment location: /usr/miniconda3/envs/road
  added / updated specs:
    - bioconda::roadies
The following packages will be downloaded:
    package             

The following NEW packages will be INSTALLED:
  about-time         conda-forge/noarch::about-time-4.2.1-pyhd8ed1ab_0 
  aioeasywebdav      conda-forge/linux-64::aioeasywebdav-2.4.0-py39hf3d152e_1001 
  aiohappyeyeballs   conda-forge/noarch::aiohappyeyeballs-2.4.0-pyhd8ed1ab_0 
  aiohttp            conda-forge/linux-64::aiohttp-3.10.5-py39hcd6043d_0 
  aiosignal          conda-forge/noarch::aiosignal-1.3.1-pyhd8ed1ab_0 
  alive-progress     conda-forge/noarch::alive-progress-3.1.5-pyhd8ed1ab_0 
..
The following packages will be UPDATED:
  ca-certificates    pkgs/main::ca-certificates-2024.7.2-h~ --> conda-forge::ca-certificates-2024.8.30-hbcca054_0 
  libgcc-ng          pkgs/main::libgcc-ng-11.2.0-h1234567_1 --> conda-forge::libgcc-ng-14.1.0-h69a702a_1 
  libgomp              pkgs/main::libgomp-11.2.0-h1234567_1 --> conda-forge::libgomp-14.1.0-h77fa898_1 
  libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-14.1.0-h4852527_1 
  openssl              pkgs/main::openssl-3.0.15-h5eee18b_0 --> conda-forge::openssl-3.3.2-hb9d3cd8_0 
  zlib                    pkgs/main::zlib-1.2.13-h5eee18b_1 --> conda-forge::zlib-1.2.13-h4ab18f5_6 
The following packages will be SUPERSEDED by a higher-priority channel:
  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex          pkgs/main::_openmp_mutex-5.1-1_gnu --> conda-forge::_openmp_mutex-4.5-2_gnu 

Proceed ([y]/n)? y

Downloading and Extracting Packages:                                                                                                                       
InvalidArchiveError("Error with archive /usr/miniconda3/pkgs/perl-5.32.1-7_hd590300_perl5.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 22] Invalid argument: '/usr/miniconda3/pkgs/perl-5.32.1-7_hd590300_perl5/man/man3/Parse::CPAN::Meta.3'")                                                                                             
InvalidArchiveError("Error with archive /usr/miniconda3/pkgs/perl-dbd-sqlite-1.72-pl5321h031d066_1.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 22] Invalid argument: '/usr/miniconda3/pkgs/perl-dbd-sqlite-1.72-pl5321h031d066_1/man/man3/DBD::SQLite::VirtualTable::FileContent.3'") 
...  
InvalidArchiveError("Error with archive /usr/miniconda3/pkgs/perl-digest-hmac-1.04-pl5321hdfd78af_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 22] Invalid argument: '/usr/miniconda3/pkgs/perl-digest-hmac-1.04-pl5321hdfd78af_0/man/man3/Digest::HMAC_MD5.3'")
InvalidArchiveError("Error with archive /usr/miniconda3/pkgs/perl-xml-regexp-0.04-pl5321hdfd78af_3.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 22] Invalid argument: '/usr/miniconda3/pkgs/perl-xml-regexp-0.04-pl5321hdfd78af_3/man/man3/XML::RegExp.3'")

```
I also did `conda clean -a` but it didn't help.  
Thank you in advance.

**Comment by ang037** [comment]
Hi, it looks like there might be an issue with your Miniconda installation. I’ve just tested the process on a different machine, and it worked fine for me. Could you try removing the current installation and reinstalling Miniconda3 on your system by following these steps?
```
rm -rf ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod +x Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh

export PATH="$HOME/miniconda3/bin:$PATH"
source ~/.bashrc
```

Also, could you please let me know which machine you are trying to run this on?

**Comment by usergenomics13** [comment]
Thanks for the response and the suggestion. Unfortunately, removing the whole conda does not seem practical for my case as I have other environments for other projects. I'm using an institutional machine of `Rocky Linux, x86_64, CPU Intel Xeon`. 

I've also tried to install roadies in another machine of `Red Hat Enterprise Linux, x86_64, AMD EPYC` and the installation has stuck at this for a while. I'm wondering whether it can take a few hours?

```
$ conda install roadies
Collecting package metadata (current_repodata.json): - WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: | 
```
Thanks for your help

**Comment by usergenomics13** [comment]
Update:
In the second machine (RedHat), after around 1.5 hours, it finished with this
```
...
 zlib               conda-forge/linux-64::zlib-1.3.1-h4ab18f5_1
  zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0
Proceed ([y]/n)? y
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: - | |done
Executing transaction: \
For Linux 64, Open MPI is built with CUDA awareness but this support is disabled by default.
To enable it, please set the environment variable OMPI_MCA_opal_cuda_support=true before
launching your MPI processes. Equivalently, you can set the MCA parameter in the command line:
mpiexec --mca opal_cuda_support 1 ...

In addition, the UCX support is also built but disabled by default.
To enable it, first install UCX (conda install -c conda-forge ucx). Then, set the environment
variables OMPI_MCA_pml="ucx" OMPI_MCA_osc="ucx" before launching your MPI processes.
Equivalently, you can set the MCA parameters in the command line:
mpiexec --mca pml ucx --mca osc ucx ...
Note that you might also need to set UCX_MEMTYPE_CACHE=n for CUDA awareness via UCX.
Please consult UCX's documentation for detail.
```
I can see some files but it seems the installation wasn't successful. 
```
 ls /wrk/miniconda/envs/road/ROADIES/
ASTER-Linux         config      drawing_github.png  metadata_conda_debug.yaml  README.md        run_roadies.py
build_env_setup.sh  Dockerfile  LICENSE             mkdocs.yml                 reference_trees  test
conda_build.sh      docs        Linux.zip           __pycache__                roadies_env.sh   workflow
```
because  if I run `run_roadies.py` from the downloaded github repo
```
 $ python ROADIES-main/run_roadies.py --cores 1
rm: cannot remove 'output_files': No such file or directory
Unlocking working directory.
snakemake --cores 1 --config mode=accurate config_path=config/config.yaml num_threads=0 --use-conda --rerun-incomplete
Config file config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
CreateCondaEnvironmentException:
The 'mamba' command is not available in the shell /usr/bin/bash that will be used by Snakemake. You have to ensure that it is in your PATH, e.g., first activating the conda base environment with `conda activate base`.The mamba package manager (https://github.com/mamba-org/mamba) is a fast and robust conda replacement. It is the recommended way of using Snakemake's conda integration. It can be installed with `conda install -n base -c conda-forge mamba`. If you still prefer to use conda, you can enforce that by setting `--conda-frontend conda`.
sh: ./workflow/scripts/get_run_noconverge.sh: Permission denied
sh: ASTER-Linux/bin/astral-pro2: No such file or directory
sh: ASTER-Linux/bin/astral-pro2: No such file or directory
Traceback (most recent call last):
  File "/wrk/ROADIES-main/workflow/scripts/noconverge.py", line 141, in <module>
    num_gt = converge_run(
  File "/wrk/ROADIES-main/workflow/scripts/noconverge.py", line 75, in converge_run
    gt = open(roadies_dir + "/genetrees/gene_tree_merged.nwk", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'output_files/genetrees/gene_tree_merged.nwk'
Traceback (most recent call last):
  File "/wrk/ROADIES-main/run_roadies.py", line 17, in <module>
    subprocess.run(
  File "/wrk/miniconda/envs/road/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'workflow/scripts/noconverge.py', '--cores', '1', '--mode', 'accurate', '--config', 'config/config.yaml']' returned non-zero exit status 1.
```

It seems `astral-pro2` is not installed. Conda should have installed it..
```
$ astral-pro2
-bash: astral-pro2: command not found

$ grep astral  ROADIES-main/workflow/scripts/noconverge.py
       "ASTER-Linux/bin/astral-pro2 -t {1} -u 3 
```

**Comment by ang037** [comment]
Thanks for your patience in installing the package. Looking at the snippets you provided, I see that the package has been installed successfully. However, the issue is probably caused by mamba and conda environmental conflicts.  

Unfortunately, I have not faced this exact issue, but there is a possible fix that might solve this error. Could you please make a one-line change in the existing code in the downloaded repo and try running the pipeline again? If the solution works, I'll modify the bioconda recipe to update the ROADIES package, which will fix this issue permanently. 

In the downloaded ROADIES repository, open the file `noconverge.py` inside the `workflow` folder (`ROADIES/workflow/noconverge.py`). At line 31, add one extra argument, `--conda-frontend conda` to the `cmd` command as shown below:

```
    cmd = [
        "snakemake",
        "--cores",
        str(cores),
        "--config",
        "mode=" + str(mode),
        "config_path=" + str(config_path),
        "num_threads=" + str(num_threads),
        "--use-conda",
        "--rerun-incomplete",
        "--conda-frontend", "conda"
    ]
```

Once you make that change in the file, please try rerunning the ROADIES pipeline using the following command: `python run_roadies.py --cores 16`. 

Please let me know how it goes or if you still face further issues. We have newly added the bioconda package, so your feedback and suggestions will certainly be helpful in making our tool error-free and easily accessible for future users.

**Comment by usergenomics13** [comment]
Sure. Yeah, having both mamba and conda in machine usually causes problems.  Probably you meant `workflow/scripts/noconverge.py`, so I've updated the code. Now it progressed further but at the end similar error. Please find here the full log  [roadies_log_16sept.txt](https://github.com/user-attachments/files/17021120/roadies_log_16sept.txt). 

```
rule sequence_select:
    input: test/test_data/droYak2.fa.gz
    output: output_files/samples/droYak2_temp.fa
    jobid: 17
    benchmark: output_files/benchmarks/droYak2.sample.txt
    reason: Missing output files: output_files/samples/droYak2_temp.fa
    wildcards: sample=droYak2
    threads: 0
    resources: tmpdir=/tmp

..
We are starting to sample test/test_data/droYak2.fa.gz
./workflow/scripts/sampling/build/sampling -i test/test_data/droYak2.fa.gz -o output_files/samples/droYak2_temp.fa -l 500 -s 216 -e 229 -t 0.9
/usr/bin/bash: line 3: ./workflow/scripts/sampling/build/sampling: No such file or directory

..
(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-09-16T231826.092826.snakemake.log
rm: cannot remove '/users/s/.pasta': No such file or directory
sh: ASTER-Linux/bin/astral-pro2: No such file or directory
sh: ASTER-Linux/bin/astral-pro2: No such file or directory
Traceback (most recent call last):
  File "/wrk/ROADIES-main/workflow/scripts/noconverge.py", line 142, in <module>
    num_gt = converge_run(
  File "/wrk/ROADIES-main/workflow/scripts/noconverge.py", line 76, in converge_run
    gt = open(roadies_dir + "/genetrees/gene_tree_merged.nwk", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'output_files/genetrees/gene_tree_merged.nwk'
Traceback (most recent call last):
  File "/wrk/ROADIES-main/run_roadies.py", line 17, in <module>
    subprocess.run(
  File "/wrk/miniconda/envs/road/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'workflow/scripts/noconverge.py', '--cores', '1', '--mode', 'accurate', '--config', 'config/config.yaml']' returned non-zero exit status 1.

```

I'm also wondering whether it installs all the packages for every run.

**Comment by usergenomics13** [comment]
Yes. the conda env `road` was activated when I ran the command line. (I don't have snakemake in my `base` conda env.)
From the log that I've sent earlier [roadies_log_16sept.txt](https://github.com/user-attachments/files/17021120/roadies_log_16sept.txt), it seems like snakemake is trying to create conda env again (and it doesnt use the activated conda env).

```
$ python run_roadies.py  --cores 1
Unlocking working directory.
snakemake --cores 1 --config mode=accurate config_path=config/config.yaml num_threads=0 --use-conda --rerun-incomplete --conda-frontend conda
...
Building DAG of jobs...
...
Creating conda environment workflow/envs/msa.yaml...
Downloading and installing remote packages.
...
```

**Comment by ang037** [comment]
Thanks for providing the inputs. Unfortunately, I’m not able to recreate the error on my end, so I haven’t been able to identify a solution yet. It might be helpful if we could sync up via any means (Zoom/Google Meet) to take a more detailed look at the issues you are encountering.

In the meantime, you might want to try an alternative installation method—such as using installation script if you have root access to the server or using Docker. All the instructions are provided in the repository's wiki or README.

Let me know your thoughts or if you have any questions!
